import * as dotenv from 'dotenv';

dotenv.config();

export default [
  {
    name: 'connection',
    type: 'postgres',
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    entities: ['src/**/*.entity.ts'],
    migrations: ['database/migrations/*.ts'],
    cli: {
      migrationsDir: 'database/migrations',
    },
  },
  {
    name: 'seed',
    type: 'postgres',
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    migrations: ['database/seeds/*.ts'],
    entities: ['src/**/*.entity.ts'],
    cli: {
      migrationsDir: 'database/seeds',
    },
  },
  {
    name: 'seed-fake',
    type: 'postgres',
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    migrations: ['database/seeds-fake/*.ts'],
    entities: ['src/**/*.entity.ts'],
    cli: {
      migrationsDir: 'database/seeds-fake',
    },
    logging: false,
  },
  {
    name: 'seed-fake-test',
    type: 'postgres',
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    migrations: ['database/seeds-tests-fake/*.ts'],
    entities: ['src/**/*.entity.ts'],
    cli: {
      migrationsDir: 'database/seeds-fake-test',
    },
    logging: false,
  },
  {
    name: 'seed-carga-fake',
    type: 'postgres',
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    migrations: ['database/seeds-carga-fake/*.ts'],
    entities: ['src/**/*.entity.ts'],
    cli: {
      migrationsDir: 'database/seeds-carga-fake',
    },
    logging: false,
  },
  {
    name: 'seed-carga-examen',
    type: 'postgres',
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    migrations: ['database/seeds-carga-examen/*.ts'],
    entities: ['src/**/*.entity.ts'],
    cli: {
      migrationsDir: 'database/seeds-carga-examen',
    },
    logging: false,
  },
  {
    name: 'seed-carga-empaquetado',
    type: 'postgres',
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    migrations: ['database/seeds-carga-empaquetado/*.ts'],
    entities: ['src/**/*.entity.ts'],
    cli: {
      migrationsDir: 'database/seeds-carga-empaquetado',
    },
    logging: false,
  },

  {
    name: 'seed-carga-resultados',
    type: 'postgres',
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_DATABASE,
    migrations: ['database/seeds-carga-resultados/*.ts'],
    entities: ['src/**/*.entity.ts'],
    cli: {
      migrationsDir: 'database/seeds-carga-resultados',
    },
    logging: false,
  },
];
