import { Persona } from 'src/application/persona/persona.entity';
import { TextService } from 'src/common/lib/text.service';
import { MigrationInterface, QueryRunner } from 'typeorm';

export class usuario1511171041789 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const items = [
      {
        nombres: 'JUAN',
        primerApellido: 'PEREZ',
        segundoApellido: 'PEREZ',
        nroDocumento: '9270815',
        fechaNacimiento: '2002-02-09',
        genero: 'M',
      },
      {
        nombres: 'MARIA',
        primerApellido: 'PEREZ',
        segundoApellido: 'PEREZ',
        nroDocumento: '1765251',
        fechaNacimiento: '2002-02-09',
        genero: 'F',
      },
      {
        nombres: 'PEDRO',
        primerApellido: 'PEREZ',
        segundoApellido: 'PEREZ',
        nroDocumento: '6114767',
        fechaNacimiento: '2002-02-09',
        genero: 'M',
      },
      {
        nombres: 'RICARDO',
        primerApellido: 'AGUILERA',
        segundoApellido: 'JIMENEZ',
        nroDocumento: '5602708',
        fechaNacimiento: '1983-07-21',
        genero: 'M',
      },
      {
        nombres: 'RAMON',
        primerApellido: 'RAMOS',
        segundoApellido: 'ROSALES',
        nroDocumento: '7463463',
        fechaNacimiento: '1984-05-03',
        genero: 'M',
      },
      {
        nombres: 'JULIETA',
        primerApellido: 'MEDINA',
        segundoApellido: 'POMA',
        nroDocumento: '4839423',
        fechaNacimiento: '1983-02-16',
        genero: 'F',
      },
      {
        nombres: 'WALTER',
        primerApellido: 'ARANCIBIA',
        segundoApellido: 'LOAYZA',
        nroDocumento: '4839411',
        fechaNacimiento: '1981-01-10',
        genero: 'M',
      },
      {
        nombres: 'JESSICA',
        primerApellido: 'FLORES',
        segundoApellido: 'VALDEZ',
        nroDocumento: '3439411',
        fechaNacimiento: '1986-08-10',
        genero: 'F',
      },
      {
        nombres: 'PABLO',
        primerApellido: 'DIAZ',
        segundoApellido: null,
        nroDocumento: '8769411',
        fechaNacimiento: '1976-01-10',
        genero: 'M',
      },
      {
        nombres: 'PABLO',
        primerApellido: 'SALINAS',
        segundoApellido: 'MENDEZ',
        nroDocumento: '3439412',
        fechaNacimiento: '1986-10-10',
        genero: 'M',
      },
      {
        nombres: 'MONICA',
        primerApellido: 'HERBAS',
        segundoApellido: 'DURAN',
        nroDocumento: '4839412',
        fechaNacimiento: '1975-10-10',
        genero: 'F',
      },
      {
        nombres: 'NOMBREA',
        primerApellido: 'PATERNOA',
        segundoApellido: 'MATERNOA',
        nroDocumento: '5000001',
        fechaNacimiento: '1982-10-01',
        genero: 'F',
      },
      {
        nombres: 'NOMBREB',
        primerApellido: 'PATERNOB',
        segundoApellido: 'MATERNOB',
        nroDocumento: '5000002',
        fechaNacimiento: '1982-10-02',
        genero: 'F',
      },
      {
        nombres: 'NOMBREC',
        primerApellido: 'PATERNOC',
        segundoApellido: 'MATERNOC',
        nroDocumento: '5000003',
        fechaNacimiento: '1982-10-03',
        genero: 'F',
      },
      {
        nombres: 'NOMBRED',
        primerApellido: 'PATERNOD',
        segundoApellido: 'MATERNOD',
        nroDocumento: '5000004',
        fechaNacimiento: '1982-10-04',
        genero: 'F',
      },
      {
        nombres: 'NOMBREE',
        primerApellido: 'PATERNOE',
        segundoApellido: 'MATERNOE',
        nroDocumento: '5000005',
        fechaNacimiento: '1982-10-05',
        genero: 'F',
      },
      {
        nombres: 'NOMBREF',
        primerApellido: 'PATERNOF',
        segundoApellido: 'MATERNOF',
        nroDocumento: '5000006',
        fechaNacimiento: '1982-10-06',
        genero: 'F',
      },
      {
        nombres: 'NOMBREG',
        primerApellido: 'PATERNOG',
        segundoApellido: 'MATERNOG',
        nroDocumento: '5000007',
        fechaNacimiento: '1982-10-07',
        genero: 'F',
      },
      {
        nombres: 'NOMBREH',
        primerApellido: 'PATERNOH',
        segundoApellido: 'MATERNOH',
        nroDocumento: '5000008',
        fechaNacimiento: '1982-10-08',
        genero: 'F',
      },
      {
        nombres: 'NOMBREI',
        primerApellido: 'PATERNOI',
        segundoApellido: 'MATERNOI',
        nroDocumento: '5000009',
        fechaNacimiento: '1982-10-09',
        genero: 'F',
      },
      {
        nombres: 'NOMBREJ',
        primerApellido: 'PATERNOJ',
        segundoApellido: 'MATERNOJ',
        nroDocumento: '5000010',
        fechaNacimiento: '1982-10-10',
        genero: 'F',
      },
      {
        nombres: 'NOMBREK',
        primerApellido: 'PATERNOK',
        segundoApellido: 'MATERNOK',
        nroDocumento: '5000011',
        fechaNacimiento: '1982-10-11',
        genero: 'F',
      },
      {
        nombres: 'NOMBREL',
        primerApellido: 'PATERNOL',
        segundoApellido: 'MATERNOL',
        nroDocumento: '5000012',
        fechaNacimiento: '1982-10-12',
        genero: 'F',
      },
      {
        nombres: 'NOMBREM',
        primerApellido: 'PATERNOM',
        segundoApellido: 'MATERNOM',
        nroDocumento: '5000013',
        fechaNacimiento: '1982-10-13',
        genero: 'F',
      },
      {
        nombres: 'NOMBREN',
        primerApellido: 'PATERNON',
        segundoApellido: 'MATERNON',
        nroDocumento: '5000014',
        fechaNacimiento: '1982-10-14',
        genero: 'F',
      },
      {
        nombres: 'NOMBREO',
        primerApellido: 'PATERNOO',
        segundoApellido: 'MATERNOO',
        nroDocumento: '5000015',
        fechaNacimiento: '1982-10-15',
        genero: 'F',
      },
      {
        nombres: 'NOMBREP',
        primerApellido: 'PATERNOP',
        segundoApellido: 'MATERNOP',
        nroDocumento: '5000016',
        fechaNacimiento: '1982-10-16',
        genero: 'M',
      },
      {
        nombres: 'NOMBREQ',
        primerApellido: 'PATERNOQ',
        segundoApellido: 'MATERNOQ',
        nroDocumento: '5000017',
        fechaNacimiento: '1982-10-17',
        genero: 'M',
      },
      {
        nombres: 'NOMBRER',
        primerApellido: 'PATERNOR',
        segundoApellido: 'MATERNOR',
        nroDocumento: '5000018',
        fechaNacimiento: '1982-10-18',
        genero: 'M',
      },
      {
        nombres: 'NOMBRES',
        primerApellido: 'PATERNOS',
        segundoApellido: 'MATERNOS',
        nroDocumento: '5000019',
        fechaNacimiento: '1982-10-19',
        genero: 'M',
      },
      {
        nombres: 'NOMBRET',
        primerApellido: 'PATERNOT',
        segundoApellido: 'MATERNOT',
        nroDocumento: '5000020',
        fechaNacimiento: '1982-10-20',
        genero: 'M',
      },
      {
        nombres: 'NOMBREU',
        primerApellido: 'PATERNOU',
        segundoApellido: 'MATERNOU',
        nroDocumento: '5000021',
        fechaNacimiento: '1982-10-21',
        genero: 'M',
      },
      {
        nombres: 'NOMBREV',
        primerApellido: 'PATERNOV',
        segundoApellido: 'MATERNOV',
        nroDocumento: '5000022',
        fechaNacimiento: '1982-10-22',
        genero: 'M',
      },
      {
        nombres: 'NOMBREW',
        primerApellido: 'PATERNOW',
        segundoApellido: 'MATERNOW',
        nroDocumento: '5000023',
        fechaNacimiento: '1982-10-23',
        genero: 'M',
      },
      {
        nombres: 'NOMBREX',
        primerApellido: 'PATERNOX',
        segundoApellido: 'MATERNOX',
        nroDocumento: '5000024',
        fechaNacimiento: '1982-10-24',
        genero: 'M',
      },
      {
        nombres: 'NOMBREY',
        primerApellido: 'PATERNOY',
        segundoApellido: 'MATERNOY',
        nroDocumento: '5000025',
        fechaNacimiento: '1982-10-25',
        genero: 'M',
      },
      {
        nombres: 'NOMBREZ',
        primerApellido: 'PATERNOZ',
        segundoApellido: 'MATERNOZ',
        nroDocumento: '5000026',
        fechaNacimiento: '1982-10-26',
        genero: 'M',
      },
      {
        nombres: 'NOMBREAA',
        primerApellido: 'PATERNOAA',
        segundoApellido: 'MATERNOAA',
        nroDocumento: '5000027',
        fechaNacimiento: '1982-10-27',
        genero: 'M',
      },
      {
        nombres: 'NOMBREAB',
        primerApellido: 'PATERNOAB',
        segundoApellido: 'MATERNOAB',
        nroDocumento: '5000028',
        fechaNacimiento: '1982-10-28',
        genero: 'M',
      },
      {
        nombres: 'NOMBREAC',
        primerApellido: 'PATERNOAC',
        segundoApellido: 'MATERNOAC',
        nroDocumento: '5000029',
        fechaNacimiento: '1982-10-29',
        genero: 'M',
      },
      {
        nombres: 'NOMBREAD',
        primerApellido: 'PATERNOAD',
        segundoApellido: 'MATERNOAD',
        nroDocumento: '5000030',
        fechaNacimiento: '1982-10-30',
        genero: 'M',
      },
    ];
    const personas = items.map((item) => {
      const p = new Persona();
      p.id = TextService.textToUuid(item.nroDocumento);
      p.nombres = item.nombres;
      p.primerApellido = item.primerApellido;
      p.segundoApellido = item.segundoApellido;
      p.tipoDocumento = 'CI';
      p.nroDocumento = item.nroDocumento;
      p.fechaNacimiento = item.fechaNacimiento;
      p.genero = item.genero;
      p.usuarioCreacion = '1';
      return p;
    });
    await queryRunner.manager.save(personas);
  }

  /* eslint-disable */
  public async down(queryRunner: QueryRunner): Promise<void> {}
}
